flipkart/accounts/urls.py
from django.urls import path
from . import views
urlpatterns=[
  path('register/',views.register,name="register"),
  path('login/',views.login,name="login"),
  path('logout/',views.logout,name="logout")
]

flipkart/cart/urls.py
from django.urls import path
from . import views

app_name="cart"
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove, name='full_remove'),

]

flipkart/flipkart/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from flipkartapp import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home,name="home"),
    path('flipkartapp/',include('flipkartapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('accounts/',include(('accounts.urls','accounts'),namespace='accounts')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

flipkart/flipkartapp/urls.py
from django.urls import path
from . import views
app_name='flipkartapp'
urlpatterns=[
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name="products_by_category"),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdCatDetail,name="ProdCatDetail"),
]

flipkart/search_app/urls.py
from django.urls import path
from . import views

app_name="search_app"
urlpatterns=[
    path('',views.searchResult,name='searchResult'),
]

flipkart/cart/models.py
from django.db import models
from flipkartapp.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self):
        return self.product

flipkart/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from flipkartapp.models import Product
from . models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
         cart=Cart.objects.create(cart_id=_cart_id(request))
         cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()

    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter+=cart_item.quantity
    except ObjectDoesNotExist:
         pass
    return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

flipkart/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

flipkart/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        welcome to the cart store where can you buy awesome items!!.
{% endblock %}
{% block title %}
    Cart - Shoap Your Favurate !!!
{% endblock %}
{% block content %}
{% if not cart_item %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">Your Shopping Cart is Empty</h1><br>
            <p class="text-center">
                Please click<a href="{% url 'flipkartapp:allProdCat' %}">Here</a>
            </p>
        </div>
    </div>
{% else %}
 <div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
    </div>
 </div>
 <div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">Your items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
              <tr>
                 <td>
                    <a href="cart_item.product.get_absolute_url"><img src={{cart_item.product.image.url}} class="float-left rounded custom_image"></a>
                 </td>
                <td class="text-lef">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Unit price: {{cart_item.product.price}}
                    QTY: {{cart_item.quantity}} x $ {{cart_item.product.price}}
                </td>
                <td>$ {{cart_item.sub_total}}</td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-minus custom_icon"></i></a> &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                   &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a> &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>

                 </td>
                {% endif %}
               </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
     <table class="table my custom_table">
         <thead class="my_custom_thead">
         <tr>
             <th>
                 Checkout
             </th>
         </tr>
         </thead>
         <tbody>
         <tr>
             <td>
                 Please review Your shopping Cart items before proceeding the order payment.
             </td>
         </tr>
         <tr>
          <td class="text-left">
              Your total is <strong>${{ total }}</strong>
          </td>
         </tr>
         </tbody>
     </table>
        <div class="mx-auto">
            <a href="{% url 'flipkartapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        </div>
   </div>
</div><br>
{% endif %}
{% endblock %}

flipkart/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.desc |truncatewords:155 }}
    {% else %}
        welcome to the cart store where can you buy awesome items!!.
    {% endif %}
{% endblock %}
{% block title %}
        {% if category %}
            {{category.name}}-Shop cart
        {% else %}
            see our collections -shop cart
        {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
<div class="text-center row my_row_class" xmlns="http://www.w3.org/1999/html">
            <div class="mx-auto">
                <p><a href="{% url 'flipkartapp:allProdCat' %}">Our product collections </a><b>{{category.name}}</b></p>
            </div>
        </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
        <img class="my_image" src="{{category.img.url}}" style="height:350px;" alt="{{category.name}}">
</div><br>
<div>
    <h1 class="text-center my title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
</div>
    {% else %}
        <div>
      <center><img class="my_image my_image_padding" src="{% static 'img/FLIPKART.png' %}" style="width:1250px;" alt=""></center>
         </div><br>
<div>
    <h1 class="text-center my_title">Shop cart collections</h1>
    <p class="text-justify">Flipkart is an e-commerce company headquartered in Bangalore, Karnataka, India, and registered in Singapore. The company initially focused on online book sales before expanding into other product categories such as consumer electronics, fashion, home essentials, groceries, and lifestyle products.</p>
</div>
    {% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.img.url}}" style="width:200px;height:250px;" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
     <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {%if products.number == pg %} activate {% endif %}">{{pg}}</a>
        {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

flipkart/templates/footer.html
<div class="footer navbar-fixed bottom my_footer">
    <p class="text-center">&copy; Avodha Training .All Rights Reserved</p>
</div>

flipkart/templates/header.html
{% load static %}
<div>
    <div>
         <center><img src="{% static 'img/fliplogo.png' %}" alt="THIS is our logo"></center>
    </div>
</div>

flipkart/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        welcome to Flipkart!!.
{% endblock %}
{% block title %}
     Login Here !
{% endblock %}
{% block content %}

<form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="password" name="password" placeholder="password"><br>
    <input type="submit" value="Login">
</form>
{% endblock %}

flipkart/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}

          <li>Hai {{user.username}}</li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
          <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:register' %}">signup</a></li>

          <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
          {% endif %}

        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
             <li><a class="dropdown-item"  href="{% url 'flipkartapp:allProdCat' %}">All Products</a></li>
               {% for cat in links %}
             <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                {% endfor %}

          </ul>
        </li>
            {% if item_count > 0 %}
           <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-cart-plus"></i></a>
            </li>
          {% endif %}

      </ul>
<form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
    {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

<!--<nav>-->
<!--    <ul>-->
<!--        <li><a href="{% url 'flipkartapp:allProdCat' %}">All products</a></li>-->
<!--        {% for cat in links %}-->
<!--        <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>-->

<!--        {% endfor %}-->
<!--        <li>your cart</li>-->
<!--    </ul>-->
<!--</nav>-->

flipkart/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc|truncatewords:155}}
{% endblock %}
{% block title %}
    {{product.name}}-shop cart
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class=" mx-auto">
        <p><a href="{% url 'flipkartapp:allProdCat' %}">HOME</a> |<a href="{{product.category.get_url}}">{{product.name}}</a></p>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width:18rem;">
                <img src="{{product.img.url}}" style="width:150px;height:170px" alt="{{product.name}}">
<!--               </div>-->
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">
            <div>
                <h1 class="my_prod_title">{{product.name}}</h1>
                <p>${{product.price}}</p>
                <p class="my_title">Product Description</p>
                <p class="text-justify my_prod_text">{{product.desc}}</p>
                {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b>Out of stock</b></p>
                {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                {% endif %}


              </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

flipkart/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        welcome to the cart store where can you buy awesome items!!.
{% endblock %}
{% block title %}
     Sign up Here !
{% endblock %}
{% block content %}
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="text" name="first_name" placeholder="firstname"><br>

    <input type="text" name="last_name" placeholder="last_name"><br>

    <input type="email" name="email" placeholder="email"><br>

    <input type="password" name="password1" placeholder="password"><br>

    <input type="password" name="password2" placeholder="confirm password"><br>

    <input type="submit" value="Sign Up">

</form>
<div>
    {% for message in messages %}
    <h4>{{message}}</h4>
    {% endfor %}
</div>

{% endblock %}

flipkart/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc|truncatewords:155}}
{% endblock %}
{% block title %}
    {{product.name}}-shop cart
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">you have search for: {{query}}</p>
</div>
<div class="container">
    <div class="row max-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.img.url}}" style="width:200px;height:250px;" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found.</p>
        </div>
        {% endfor %}
    </div>
  </div>

{% endblock %}